set -g default-shell "/usr/bin/fish"
#set -g default-shell "/usr/local/bin/zsh"
#set -g default-terminal "screen-256color"
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# prefix
set-option -g prefix C-Space
bind-key C-Space send-prefix

# emacs -nw evil-mode compat
set -s escape-time 0

# copy mode
set -w -g mode-keys vi
bind Escape copy-mode

# splitting panes
unbind %
bind / split-window -h # horizontal split
unbind '"'
bind - split-window -v # vertical split

# moving around panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind J swap-pane -D
bind K swap-pane -U
bind b break-pane
bind s command-prompt -p "send pane to:"  "join-pane -t ':%%'"
set -g display-panes-time 800 # increase prefix q display time

# moving between windows
bind Enter new-window
bind Tab last-window # move to last active window
bind Space command-prompt -p "search windows for:" "find-window '%%'"
set -g renumber-windows on

# pane resizing
bind Left resize-pane -L 10
bind Right resize-pane -R 10
bind Down resize-pane -D 10
bind Up resize-pane -U 10
bind C-Left resize-pane -L
bind C-Right resize-pane -R
bind C-Down resize-pane -D
bind C-Up resize-pane -U
bind L next-layout

# session management
bind C-c new-session
#bind C-Space command-prompt -p "switch to session:" "switch-client -t '%%'"

# status bar
#set -g status-bg colour234
#set -g status-fg colour164
set -g status-bg '#037178'
set -g status-fg '#bfc204'
set -g pane-border-indicators both
set -g pane-border-lines heavy
set -g pane-active-border-style 'fg=#037178'
set -g pane-border-style 'fg=#101010'

# misc
set -w -q -g utf8 on
set -g history-limit 5000
set -w -g automatic-rename on # rename window for current program
set -g renumber-windows on # renumber when a window is closed
bind R source-file /home/vilmibm/.tmux.conf \; display-message " Config reloaded."
